version: '3.2'
services:
  p4d.helix:
    build:
      context: helix-p4d
      dockerfile: Dockerfile
    hostname: p4d
    domainname: helix
    ports:
      - 4000:1666
    volumes:
      - ./data/helix-p4d:/p4
    tty: true
    environment:
    - P4NAME=$P4NAME
    - P4TCP=$P4TCP
    - P4PORT=$P4TCP
    - P4USER=$P4USER
    - P4PASSWD=$P4PASSWD
    - P4CASE=$P4CASE
    - P4CHARSET=$P4CHARSET
    - SECURITY=$SECURITY

  redis.helix:
    image: redis:alpine
    command: redis-server --requirepass ${REDISPASSWORD}
    hostname: redis
    domainname: helix
    expose:
     - 6379
    volumes:
     - ./tmp/redis:/data
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  swarm.helix:
    build:
      context: helix-swarm
      dockerfile: Dockerfile
    hostname: swarm
    domainname: helix
    ports:
      - 5080:80
    depends_on:
      - redis.helix
      - p4d.helix
    tty: true
    environment:
     - P4PORT=$P4PORT
     - P4USER=$P4USER
     - P4PASSWD=$P4PASSWD
     - SWARMHOST=$SWARMHOST
     - SWARMUSER=$SWARMUSER
     - SWARMPASSWD=$SWARMPASSWD
     - SWARMTOKEN=$SWARMTOKEN
     - REDISPASSWORD=$REDISPASSWORD
     - MAILHOST=$MAILHOST
     - BASE_URL=$BASE_URL